# Generated by Django 6.0.2 on 2026-02-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(2, 'Admin'), (3, 'Student')], default=3),
        ),
    ]
