# Generated by Django 6.0.2 on 2026-02-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Admin'), (3, 'Student')], default=3),
        ),
    ]
