# Generated by Django 5.2.4 on 2026-05-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(blank=True, default='', help_text='ID card number', max_length=20),
        ),
    ]
