# Generated by Django 6.0.1 on 2026-02-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevelprogress',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
