# Generated by Django 5.2.4 on 2026-03-05 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userlevelprogress_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('first_level', 'First Level Completed'), ('level_streak', 'Level Streak'), ('perfect_score', 'Perfect Score'), ('total_levels', 'Total Levels Completed'), ('discipline_master', 'Discipline Master'), ('star_collector', 'Star Collector'), ('speed_runner', 'Speed Runner'), ('persistent', 'Persistent Player')], max_length=20)),
                ('icon', models.CharField(default='bi-trophy', max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=20)),
                ('condition_value', models.IntegerField(default=1, help_text='Value needed to unlock achievement')),
                ('points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress_value', models.IntegerField(default=0, help_text='Current progress towards achievement')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
