# Generated by Django 5.2.4 on 2026-03-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userlevelprogress_attempts_time_levelattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
