# Generated by Django 5.2.4 on 2026-04-06 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_achievement_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_levels', to=settings.AUTH_USER_MODEL),
        ),
    ]
