# Generated by Django 5.2.4 on 2026-04-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_level_assigned_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='theme',
            field=models.CharField(choices=[('none', 'Sin temática'), ('tortoise_hare', 'La Liebre y la Tortuga')], default='none', help_text='Visual theme for the level gameplay', max_length=30),
        ),
        migrations.AddField(
            model_name='level',
            name='time_limit_seconds',
            field=models.IntegerField(default=300, help_text='Time limit in seconds (used by timed themes like Tortoise & Hare)'),
        ),
    ]
