# Generated by Django 5.2.4 on 2026-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_level_theme_level_time_limit_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='theme',
            field=models.CharField(choices=[('none', 'Sin temática'), ('tortoise_hare', 'La Liebre y la Tortuga'), ('mountain_climb', 'Escalada de Montaña')], default='none', help_text='Visual theme for the level gameplay', max_length=30),
        ),
    ]
