# Generated by Django 5.2.4 on 2026-04-07 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_questionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_images', to='core.level'),
        ),
    ]
