# Generated by Django 5.2.4 on 2026-04-27 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_questionimage_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('tutor', 'Tutor IA (Estudiante)'), ('generate', 'Generar Preguntas (Profesor)')], default='tutor', max_length=20)),
                ('prompt', models.TextField(help_text='Texto enviado por el usuario a la IA')),
                ('response', models.TextField(help_text='Respuesta recibida de la IA')),
                ('tokens_used', models.IntegerField(default=0, help_text='Tokens consumidos en esta interacción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
