# Generated by Django 5.2.4 on 2026-05-07 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_classroom_classroomenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='core.discipline'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disciplines', to=settings.AUTH_USER_MODEL),
        ),
    ]
